# Generated by Django 3.0.6 on 2020-07-20 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200720_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
