# Generated by Django 3.0.6 on 2020-07-21 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200721_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Sid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
