# Generated by Django 3.0.6 on 2020-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200721_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Sid',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
