# Generated by Django 3.0.6 on 2020-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200721_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catagory',
            field=models.CharField(choices=[('Web_Development', 'Web Development'), ('App_Development', 'App Development'), ('Game_Development', 'Game Development'), ('Software_development', 'Software Development'), ('Graphic_Design', 'Graphic Design'), ('Bussiness_Management', 'Bussiness Management'), ('Study_And_Assignment', 'Study And Assignment'), ('Script', 'Script'), ('Other', 'Other')], default='Web_Development', max_length=20),
        ),
    ]
