# Generated by Django 3.0.6 on 2020-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200721_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Sid',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(blank=True, default=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
