# Generated by Django 3.0.6 on 2020-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biox',
            name='myFb',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AlterField(
            model_name='biox',
            name='myGit',
            field=models.URLField(default='https://github.com/404'),
        ),
    ]
