# Generated by Django 3.0.6 on 2020-07-23 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20200721_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('toAdmin', models.CharField(default='Empty', max_length=100)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectName_set', to='projects.Project')),
                ('reqUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqUser_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='biox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userBio', models.TextField(default='Bio is Empty. Please update Profile', max_length=250)),
                ('myGit', models.URLField(default=None)),
                ('Cuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
