# Generated by Django 3.0.6 on 2020-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_sdiscussion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdiscussion',
            name='title',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
