# Generated by Django 3.0.6 on 2020-07-27 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20200727_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdiscussion',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
